ShoppingCart/src/java/model/ProductCart.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;


import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.servlet.http.HttpSession;
import javax.websocket.Session;

/**
 *
 * @author nam oio
 */
public class ProductCart {
     
    
    private final  List cartItems;
    public  ProductCart(){
        cartItems=new ArrayList();
    }
    private List product;
    
    
    public List getProducts(){
        List temp=new ArrayList();
        try{
             Connection connection = new DBConnection().getConnection();
       Statement s=connection.createStatement();
       ResultSet rs=s.executeQuery("select * from CART");
            while (rs.next()) {                
                Product item=new Product();
                item.setProductId(1);
                item.setProductName("b");
                item.setProductType("1");
                item.setPrice(1);
                System.out.println("tt");
               temp.add(item);
            }
        
        }
        catch(Exception e){
            
        }
        return temp;
    }
     public List<Product> getAccount() {
       
       
        
                try {
                    try {
                        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver").newInstance();
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(ProductCart.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (InstantiationException ex) {
                        Logger.getLogger(ProductCart.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IllegalAccessException ex) {
                        Logger.getLogger(ProductCart.class.getName()).log(Level.SEVERE, null, ex);
                    }
                
            
            String url = "jdbc:sqlserver://localhost:1433;databaseName=sc";
            String username = "sa";
            String password = "123456";
            Connection connection = DriverManager.getConnection(url, username, password);
            System.out.println("Connected: " + connection.getClientInfo());
            java.sql.Statement st = connection.createStatement();
            String query = "select * from cart ";;

            ResultSet rs = st.executeQuery(query);
  List<Product> products = new LinkedList<>();
            if (rs != null) {
                while (rs.next()) {
                     Product item=new Product();
                item.setProductId(rs.getInt(1));
                item.setProductName(rs.getString(2));
                item.setProductType(rs.getString(3));
                item.setPrice((float) rs.getFloat(4));
                System.out.println("tt");
               products.add(item);

                }
            }

            rs.close();
            st.close();
            connection.close();
           
            return products;
        } catch (SQLException e) {
            e.printStackTrace();
            return null;
        }

    }

    
    public List<Product> getall() {

        try {
            Connection connection = new DBConnection().getConnection();
            Statement stmt2 = connection.createStatement();
            ResultSet rs = stmt2.executeQuery("select * from CART");
            List<Product> products = new LinkedList<>();
            while (rs.next()) {
                
                 Product item=new Product();
                item.setProductId(rs.getInt(1));
                item.setProductName(rs.getString(2));
                item.setProductType(rs.getString(3));
                item.setPrice((float) rs.getFloat(4));
                System.out.println("tt");
               products.add(item);
            }
            return products;

        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
   
    
    public void addItem(int productId, String productName, String productType, float price,int quantity) {
        Product item=null;
        boolean match = true;
        for(int i=0;i<cartItems.size();i++){
            System.out.println(i+"+"+((Product) cartItems.get(i)).getProductId());
          if(((Product) cartItems.get(i)).getProductId()==productId)
          {
              item =(Product) cartItems.get(i);
              setAmount(getAmount()+quantity * item.getPrice());
              item.setQuantity(item.getQuantity()+quantity);
               
              match=false;
              break;
          }
        }
        if(match){
            System.out.println("cr");
            item=new Product();
            item.setProductId(productId);
            item.setPrice(price);
            item.setProductName(productName);
            item.setProductType(productType);
            item.setQuantity(quantity);
            setAmount(getAmount()+quantity * item.getPrice());
            cartItems.add(item);
        }
    }
    public void removeItem(int productId){
        for(int i=0;i<cartItems.size();i++){
            Product item=(Product) cartItems.get(i);
            if(item.getProductId()==productId){
                setAmount(getAmount()-item.getPrice()*item.getQuantity());
                cartItems.remove(i);
                break;
            }
        }
    }
      
    
    
       public int dem(){
          return cartItems.size();
            }
    public List getCartItems(){
        return cartItems;
    }
    
    private float amount;
    public float getAmount(){
        return this.amount;
    }
    
    public void setAmount(float amount){
        this.amount=amount;
    }
}

ShoppingCart/web/card.jsp
<%-- 
    Document   : card
    Created on : Mar 20, 2018, 4:22:23 PM
    Author     : nam oio
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<jsp:useBean id="prod" class="model.ProductCart" scope="session"/>

<ceter>
    <table border="1" bgcolor="lighgreen" cellspacing="0" cellpadding="0">
        <tr>
            <td>
                <b> Product Id</b></td>
            <td><b> Product Name</b></td>
            <td><b> Product Type</b></td>
            <td><b> Price </b></td>
            <td><b> Quantity </b></td>
        </tr>
  

        <c:forEach var="item" items="${prod.cartItems}">
        <tr>

            <td>${item.productId}</td>
            <td>${item.productName}</td>
            <td>${item.productType}</td>
            <td>${item.price}</td>
            <td>${item.quantity}</td>
            <td>
                <form action="ShoppingServlet" name="deleteForm" method="post">
                    <input type="submit" value="Delete"/>
                    <input type="hidden" name="delItem" value="${item.productId}"/>
                    <input type="hidden" name="action" value="DELETE"/>

                </form>

            </td>
        </tr>
    </c:forEach>
         </table>
    
    <form name="checkoutForm" action="ShoppingServlet" method="post">
        <input type="hidden" name="action" value="CHECKOUT"/>
        <input type="submit" name="Checkout" value="Checkout"/>
    </form>
</ceter>

ShoppingCart/web/checkout.jsp
<%-- 
    Document   : checkout
    Created on : Mar 20, 2018, 4:22:37 PM
    Author     : nam oio
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<jsp:useBean id="prod" class="model.ProductCard" scope="session"/>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
    <center>
        <table>
           <tr>
            <td>
                <b> Product Id</b></td>
            <td><b> Product Name</b></td>
            <td><b> Product Type</b></td>
            <td><b> Price </b></td>
            <td><b> Quantity </b></td>
        </tr>
        
         <c:forEach var="item" items="${prod.cart.Items}">
        <tr>

            <td><${item.productId}/td>
            <td><${item.productName}/td>
            <td><${item.productType}/td>

            <td><${item.price}/td>
            <td><${item.quantity}/td>
            
        </tr>
    </c:forEach>
        <td></td>
        <td></td>
        <td><b>Total</b></td>
        <td><b>${prod.amount}</b></td>
        </table>
        <br>
        <a href="index.jsp">Home</a>
        
    </center>
    </body>
</html>

ShoppingCart/web/index.jsp
<%-- 
    Document   : index
    Created on : Mar 20, 2018, 4:20:16 PM
    Author     : nam oio
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<jsp:useBean id="prod" class="model.ProductCart" scope="session"/>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h1>Hello World!</h1>
     
        <form action="ShoppingServlet" name="shoppingForm" method="post">
            <b>Product</b>  
            <select name="products">
                <c:forEach var="item" items="${prod.account}">
                    <option>
                        
                   
                        ${item.productId}${"|"}${item.productName}${"|"}${item.productType}${"|"}${item.price}${"|"}
                         </option>
                   
                </c:forEach>
            </select>
            <br>
            <br>
            <b>Quanity</b><input type="text" name="qty" value="1"><br>
            <input type="hidden" name="action" value="ADD"/>
            <input type="submit" name="Sumbit" value="Add to Cart"/>
        </form>
        <p>${mesage}</p>
        <jsp:include page="cart.jsp" flush="true" />
    </body>
</html>

ShoppingCart/web/shoppingError.jsp
<%-- 
    Document   : shoppingError
    Created on : Mar 20, 2018, 4:22:56 PM
    Author     : nam oio
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h1>Error Occurred</h1>
        ${message}
        <a href="index.jsp">Home</a>
    </body>
</html>